# Generated by Django 4.2.4 on 2023-08-27 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('coupons', models.PositiveIntegerField()),
                ('working', models.BooleanField(default=True)),
                ('main_picture', models.ImageField(upload_to='images/offerspics/<built-in function id>/')),
                ('highlights', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('old_price', models.FloatField()),
                ('new_price', models.FloatField()),
                ('isVip', models.BooleanField()),
                ('is_unique', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(to='offers.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.location')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.category')),
            ],
            options={
                'verbose_name_plural': 'subcategories',
            },
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inner_pic', models.ImageField(upload_to='offers/<django.db.models.fields.related.ForeignKey>/')),
                ('parent_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offer')),
            ],
        ),
        migrations.CreateModel(
            name='OfferDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offer')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='sub',
            field=models.ManyToManyField(to='offers.subcategory'),
        ),
    ]
