# Generated by Django 4.2.4 on 2023-08-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_offer_main_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='compensations',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='offer',
            name='fine_print',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
