# Generated by Django 4.2.4 on 2023-08-31 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_alter_feedbacks_feedback_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacks',
            name='offer',
        ),
        migrations.AddField(
            model_name='offer',
            name='feedbacks',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='offers.feedbacks'),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='feedback_content',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
