# Generated by Django 4.2.4 on 2023-08-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_remove_feedbacks_offer_offer_feedbacks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='feedback_content',
            field=models.CharField(default='', max_length=500),
        ),
    ]
