# Generated by Django 4.2.4 on 2023-08-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_alter_feedbacks_feedback_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='feedback_content',
            field=models.CharField(blank=True, default=[], max_length=500, null=True),
        ),
    ]
