# Generated by Django 4.2.4 on 2023-08-31 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_remove_offer_feedbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='offers.offer'),
        ),
    ]
