# Generated by Django 4.2.4 on 2023-09-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_alter_feedbacks_feedback_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='parent_category',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='parent_category',
            field=models.ManyToManyField(to='offers.category'),
        ),
    ]
