# Generated by Django 4.2.4 on 2023-09-08 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0013_remove_subcategory_parent_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='parent_category',
        ),
        migrations.AddField(
            model_name='category',
            name='Subcategories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.subcategory'),
        ),
    ]
