# Generated by Django 4.2.4 on 2023-08-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_rename_title_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='location',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
    ]
