# Generated by Django 4.2.4 on 2023-08-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_location_lat_location_lng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='location_description',
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default='Beirut', max_length=50),
        ),
    ]
